@PatientService_HostAddress = http://localhost:5247

### ============================================
### GET - Récupérer tous les patients
### ============================================

GET {{PatientService_HostAddress}}/api/patients
Accept: application/json

###

### ============================================
### GET - Récupérer un patient par son ID
### ============================================

GET {{PatientService_HostAddress}}/api/patients/1
Accept: application/json

###

### ============================================
### POST - Ajouter un patient
### ============================================

POST {{PatientService_HostAddress}}/api/patients
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Martin",
  "dateOfBirth": "1985-02-10T00:00:00",
  "gender": "F"
}

###

###

###

### ============================================
### PUT - Modifier le patient 1
### ============================================

PUT {{PatientService_HostAddress}}/api/patients/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "John",
  "lastName": "Test",
  "dateOfBirth": "1990-05-15T00:00:00",
  "gender": "M",
  "address": "20 rue de Rouen",
  "phoneNumber": "0601020304"
}



###
@PatientService_HostAddress = https://localhost:7165
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ1NjE5YjhmLTVkNTYtNDVhMy05MjlkLTY0OTJhZWI1ZDBmMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im1lZGVjaW5AbWVkaXNjcmVlbi5mciIsImV4cCI6MTc4OTg5NjQ3NiwiaXNzIjoiTWVkaXNjcmVlbkF1dGhTZXJ2aWNlIiwiYXVkIjoiTWVkaXNjcmVlbkFwcGxpY2F0aW9uIn0.GmwRUP4_4BMpB5yazUn2geDcLXjM5a31kXSWgvC5ShA

GET {{PatientService_HostAddress}}/api/patients
Authorization: Bearer {{token}}

###