@Gateway_HostAddress = http://localhost:5271

### ============================================
### GET - Tous les patients via la Gateway
### ============================================

GET {{Gateway_HostAddress}}/api/patients
Accept: application/json

###

### ============================================
### GET - Un patient via la Gateway
### ============================================

GET {{Gateway_HostAddress}}/api/patients/1
Accept: application/json

###

POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
  "email": "medecin@mediscreen.fr",
  "password": "CHANGE_ME"
}

###
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "medecin@mediscreen.fr",
  "password": "CHANGE_ME"
}
